stages:
  - deploy
deploy_production:
  stage: deploy
  script:
    - rsync -av * /var/www/html/spacecom.uz/ --no-perms --no-owner --no-group --omit-dir-times
    - cd /var/www/html/spacecom.uz/
    - YII_ENV=prod php ./init --env=Production --overwrite=All
    - composer install
    - YII_ENV=prod php ./yii migrate/up --interactive=0
  environment:
    name: production
    url: http://new.spacecom.uz/
  only:
    - master
